language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

# command to install dependencies
# setup anaconda
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # install packages
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib networkx
  - source activate test-environment
  - pip install -r requirements.txt

  # for debugging purposes:
  # - echo $PATH
  # - echo $PYTHONPATH
  # - which python
  # - cd ~
  # - cd miniconda
  # - cd bin
  # - ls


# command to run tests
script: py.test