language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

# command to install dependencies
# setup anaconda
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -y conda
  - conda create -n test
  - source activate test
# install packages
  - conda install -y numpy scipy matplotlib networkx biopython
  - echo $PATH
  - echo $PYTHONPATH
  - which python


# command to run tests
script: py.test